### ISSUE TITLE
Licence lacking

### ISSUE THREAD

**Issue by smolendawid** [rozeappletree/RecSys-revamped-Python-3.6#1]
I'd like to know what is the license of your code. Could you please add it? @rakesh4real

**Comment by rozeappletree** [comment]
Hey @smolendawid, code is free to use. It was from a course it saw quite a while back [original source](https://sundog-education.com/recsys/). I did **NOT** write any of that code. Associated blog written by me can be found [here](https://medium.com/fnplus/everything-you-need-to-know-about-recommendation-systems-348cdfccbaf0)

**Comment by smolendawid** [comment]
Thanks for the response. In fact, I don't think it's mentioned anywhere that the code is free to use.
